# Generated by Django 4.0.4 on 2022-10-13 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pict',
            field=models.FileField(default=django.utils.timezone.now, upload_to='app/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
